# Generated by Django 4.0.1 on 2022-11-04 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhomeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
