# Generated by Django 4.0.1 on 2022-11-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainhomeapp', '0002_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'admin_signup',
            },
        ),
    ]
