# Generated by Django 4.0.1 on 2022-11-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='image',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='price',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.TextField(max_length=100),
        ),
    ]
