# Generated by Django 4.0.1 on 2022-11-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_grocery_description_alter_grocery_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=100)),
                ('product_quantity', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
